#!/bin/sh /etc/rc.common
# Example script
# Copyright (C) 2007 OpenWrt.org

START=10
STOP=15

start() {
    echo "Starting new process"
    cd /opt/hip-vpls/
    /sbin/ethtool -K r1-eth0 rx off tx off sg off 
    /sbin/ethtool -K r1-eth1 rx off tx off sg off 
    pid=`ps | grep switchd.py | grep python3 | awk -F" " '{print $1}'`
    if [ -z "$pid" ]; then
        python3 switchd.py &
    fi;
}

stop() {
    echo "Killing the switchd.py process"
    pid=`ps | grep switchd.py | grep python3 | awk -F" " '{print $1}'`
    kill -9 $pid
}
